# Generated by Django 4.1.2 on 2022-10-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj2app', '0002_resort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='details',
            new_name='location',
        ),
    ]
